source 'https://rubygems.org'

gem 'faye-websocket'
gem 'eventmachine'
gem 'nokogiri'
gem 'cleverbot-api', git: 'git://github.com/neilgupta/cleverbot-api.git'
gem 'rest-client'
gem 'hyoka'
gem 'pry'
gem 'pry-byebug'
gem 'faraday'
gem 'byebug'
