source 'https://rubygems.org'

gem 'faye-websocket'
gem 'eventmachine'
gem 'nokogiri'
gem 'cleverbot-api', git: 'git://github.com/neilgupta/cleverbot-api.git'
gem 'hyoka'
gem 'faraday'
gem 'byebug'
gem 'colorize'
gem 'time-lord'
gem 'time_diff'