bots:
    -
        user: 
        pass:
        rooms: ['lobby']
        server: 000.000.000:8000
        owner: 
        symbol:
        log:

#if you want to run another bot at the same time, add a '-', like above, and follow the format.